parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: jhac
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 15339d8wwwc722be6c30ce36fd2e568c9
    database_path: null
    app_url: http://local.just-had-a-cocktail.pagodabox.com:8080
    facebook_client_id: 264941376960009
    facebook_client_secret: 812f8e59f9ef74a1e84bdce6b7e3de20
    twitter_client_id: p9PuLPGrK103Wf6AyBw
    twitter_client_secret: 5A32Ev1A6wSvDEGRpZwnt7GNs9pazw6yRZaM2BH3M